spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cdc
    username: postgres
    password: postgres
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/testdb?replicaSet=rs0
      database: testdb
